<?php
/**
 * TL_ROOT/system/modules/simplepoll/languages/fr/default.php 
 * 
 * Contao extension: simplepoll 1.3.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2011-2012 Kamil Kuzminski 
 * License   : LGPL 
 * Author    : Kamil Kuzminski (qzminski), http://qzminski.com 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['simplepoll']['0'] = "Sondage";
$GLOBALS['TL_LANG']['CTE']['simplepoll']['1'] = "Affiche un sondage.";
$GLOBALS['TL_LANG']['MSC']['loginToVote'] = "Veuillez, s'il vous plaît, vous identifier pour voter.";
$GLOBALS['TL_LANG']['MSC']['vote'] = "Voter";
$GLOBALS['TL_LANG']['MSC']['showResults'] = "Afficher les résultats";
$GLOBALS['TL_LANG']['MSC']['voteSubmitted'] = "Merci d'avoir voté !";
$GLOBALS['TL_LANG']['MSC']['pollClosed']    = 'Ce sondage est clos.';
 
?>
