<?php
/**
 * TL_ROOT/system/modules/simplepoll/languages/fr/modules.php 
 * 
 * Contao extension: simplepoll 1.3.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2011-2012 Kamil Kuzminski 
 * License   : LGPL 
 * Author    : Kamil Kuzminski (qzminski), http://qzminski.com 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['simplepoll']['0'] = "Sondages";
$GLOBALS['TL_LANG']['MOD']['simplepoll']['1'] = "Gérer les sondages et leurs options.";
$GLOBALS['TL_LANG']['FMD']['simplepoll']['0'] = "Sondage";
$GLOBALS['TL_LANG']['FMD']['simplepoll']['1'] = "Affiche un sondage sur la page.";
 
?>
